- name: Update APT package cache
  apt: update_cache=yes
  changed_when: false

- name: Install system packages
  apt:
    name:
      - sudo
      - software-properties-common
      - build-essential
      - supervisor
      - nginx
      - openssl
      - libssl-dev
      - libffi-dev
      - python-dev
      - redis-server
      - cron
    state: latest
  notify:
    - reload systemd
    - start redis-server

# On the newer versions of redis, by default redis
# binds to localhost on ipv6 address which wouldn't
# let the service start if the server doesn't have
# ipv6 enabled. Hence, we set redis to listen on ipv4
- name: set redis to listen on ipv4
  notify: start redis-server
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind 127\.0\.0\.1 ::1'
    line: 'bind 127.0.0.1'
    backrefs: yes

- name: Install spatialite
  when: openwisp2_database.engine == "django.contrib.gis.db.backends.spatialite"
  apt:
    name:
      - sqlite3
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
    state: latest
  notify: reload systemd

- name: Install mod-spatialite (may fail on older linux distros)
  when: openwisp2_database.engine == "django.contrib.gis.db.backends.spatialite"
  ignore_errors: yes
  apt: name=libsqlite3-mod-spatialite state=latest

# fixes issue described in https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
- name: Install acl if acting as non-root user
  apt: name=acl state=latest
  when: ansible_user is not defined or ansible_user != 'root'

- name: ensure supervisor is started
  service: name=supervisor state=started

- name: Install python2 packages
  when: openwisp2_python in ["python2.7", "python2"]
  apt:
    name:
      - python-pip
      - python-dev
      - python-virtualenv
    state: latest

- name: Install python3 packages
  when: openwisp2_python == "python3"
  apt:
    name:
      - python3
      - python3-pip
      - python3-dev
      - python-virtualenv
    state: latest

- name: Install python3-pyparsing
  when: ansible_distribution == "Debian" and ansible_distribution_version == "9.0"
  apt:
    name:
      - python3-pyparsing
    state: latest

- name: Install python wheel (optional, allowed to fail)
  ignore_errors: yes
  apt:
    name:
      - python-wheel
      - python3-wheel
    state: latest

- name: Install python3-virtualenv
  ignore_errors: yes
  when: ansible_distribution != 'Ubuntu'
  apt:
    name:
      - python3-virtualenv
    state: latest

- name: Install ntp
  when: openwisp2_install_ntp
  apt:
    name: ntp
    state: latest
