---

- name: Install epel-release (if RedHat/Centos)
  when: ansible_distribution in ['RedHat', 'CentOS']
  yum: name=epel-release state=latest
  notify: reload systemd

- name: Install system packages
  package: name={{ item }} state=latest
  notify:
    - reload systemd
    - start redis
  with_items:
    - sudo
    - gcc
    - supervisor
    - nginx
    - openssl
    - openssl-devel
    - libffi-devel
    - python-devel
    - redis
    - redhat-rpm-config
    - cronie

- name: Install python2 system packages
  when: ansible_python_interpreter == "/usr/bin/python"
  package: name={{ item }} state=latest
  notify:
    - reload systemd
  with_items:
    - libsemanage-python
    - policycoreutils-python

- name: Install python3 system packages
  when: ansible_python_interpreter == "/usr/bin/python3"
  package: name={{ item }} state=latest
  notify:
    - reload systemd
  with_items:
    - libsemanage-python3
    - policycoreutils-python3

# On the newer versions of redis, by default redis
# binds to localhost on ipv6 address which wouldn't
# let the service start if the server doesn't have
# ipv6 enabled. Hence, we set redis to listen on ipv4
- name: set redis to listen on ipv4 (RedHat & CentOS)
  notify: start redis
  lineinfile:
    path: /etc/redis.conf
    regexp: '^bind 127\.0\.0\.1 ::1'
    line: 'bind 127.0.0.1'
    backrefs: yes

# Fedora 28 and above drops the package python-firewall
# and it gets replaced by python3-firewall

- name: Install python2 firewall packages
  when: ansible_python_interpreter == "/usr/bin/python"
  package: name={{ item }} state=present
  notify: reload systemd
  with_items:
    - python-firewall
    - firewalld

- name: Install python3 firewall packages
  when: ansible_python_interpreter == "/usr/bin/python3"
  package: name={{ item }} state=present
  notify: reload systemd
  with_items:
    - python3-firewall
    - firewalld

- name: Install spatialite
  when: openwisp2_database.engine == "django.contrib.gis.db.backends.spatialite"
  package: name={{ item }} state=latest
  notify: reload systemd
  with_items:
    - sqlite
    - gdal
    - proj-devel
    - geos-devel
    - libspatialite-devel

- name: ensure supervisor is started
  service: name=supervisord state=started enabled=yes

- name: ensure nginx is enabled
  service: name=nginx enabled=yes

- name: Install python2 packages
  when: openwisp2_python in ["python2.7", "python2"]
  package: name={{ item }} state=latest
  with_items:
    - python-pip
    - python-virtualenv

- name: Install python3 packages
  when: openwisp2_python == "python3"
  package: name={{ item }} state=latest
  with_items:
    - "{{ python3_package_prefix }}"
    - "{{ python3_package_prefix }}-pip"
    - "{{ python3_package_prefix }}-devel"

- name: Install python wheel (optional, allowed to fail)
  ignore_errors: yes
  package: name={{ item }} state=latest
  with_items:
    - python-wheel
    - "{{ python3_package_prefix }}-wheel"

- name: Install python3 virtualenv
  when: openwisp2_python == "python3" and ansible_distribution == 'Fedora'
  package:
    name: "{{ python3_package_prefix }}-virtualenv"
    state: latest

- name: (CentOS/RedHat) Always install pip
  when: ansible_distribution in ['RedHat', 'CentOS']
  package:
    name: python-pip
    state: latest

- name: (CentOS/RedHat/Fedora) Install/upgrade virtualenv via pip
  pip:
    name: virtualenv
    state: latest

- name: Install ntp
  when: openwisp2_install_ntp
  package:
    name: ntp
    state: latest
